version: "3.8"
services:
  kvstore:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - kvdata:/data
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=kvstore
      - REDIS_PORT=6379
    depends_on:
      - kvstore
    networks:
      - appnet

  client:
    build: ./client
    networks:
      - appnet
    depends_on:
      - backend

volumes:
  kvdata:

networks:
  appnet:
