---
# file: roles/nginx/tasks/main.yml
- name: Install Nginx
  apt:
    name: nginx
    state: present
  notify:
    - enable Nginx
    - start Nginx

- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: templates/etc_nginx_nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy SSL cert
  ansible.builtin.template:
    src: templates/etc_ssl_certs_localhost.crt
    dest: /etc/ssl/certs/localhost.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy SSL private key
  ansible.builtin.template:
    src: templates/etc_ssl_private_localhost.key
    dest: /etc/ssl/private/localhost.key
    owner: root
    group: root
    mode: '0644'

- name: Copy default site configuration file
  ansible.builtin.template:
    src: templates/etc_nginx_conf.d_default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart Nginx
