---
# file: roles/nginx/handlers/main.yml
- name: start Nginx
  service:
    name: nginx
    state: started

- name: restart Nginx
  service:
    name: nginx
    state: restarted

- name: enable Nginx
  service:
    name: nginx
    enabled: yes
