---
# file: playbooks/dbservers.yml
- name: Configure Database Servers
  hosts: dbservers
  become: yes
  vars:
    application_type: "{{ 'mysql' if 'mysql' in ansible_run_tags else 'sqlite' if 'sqlite' in ansible_run_tags else 'none' }}"
  roles:
    - common
    - lttng
    - role: mysql
      tags:
        - never # never run by default
        - mysql
    - role: sqlite
      tags: 
        - never # never run by default
        - sqlite
