---
# file: playbooks/dbservers.yml
- name: Configure Database Servers
  hosts: dbservers
  roles:
    - common
    - lttng
    - role: mysql
      tags: ['mysql']
    - role: sqlite
      tags: ['sqlite']
